title: "My Magazine Site"
description: "A long-form story-style static page"
url: "https://halefader.github.io"

# Optional: Turn off posts
collections:
  posts:
    output: false

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "single"
