title: "My Magazine Site"
description: "A long-form, magazine-style GitHub Pages site"
url: "https://halefader.github.io"
theme: minimal-mistakes-jekyll

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "single"
